name: Check that package version changed

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Check version
        id: check
        uses: EndBug/version-check@v2 # You can choose the version/branch you prefer.
        with:
          file-url: https://unpkg.com/dyna-record@latest/package.json
          static-checking: localIsNew

      - name: Fail if condition is false
        if: steps.check.outputs.changed == 'false'
        run: |
          echo "package.json version is not changed. Run `npm version <patch|minor|major>` and push changes."
          exit 1
